services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=java-jsf'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
