services:
  myDB:
    image: postgres
    container_name: spring-jsp-web
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=web
    volumes:
      - ./postgres:/var/lib/postgresql/data